# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'run-track' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'shared', :path => '../shared'

  pod 'GoogleMaps', '9.1.1'
  pod 'Google-Maps-iOS-Utils', '6.0.0'

  # Pods for run-track

end
